name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello, welcome to the world of open source ! Thanks you for choosing this repository for your first issue 💖 !"
        pr-message: "Hello, welcome to the world of open source ! Thanks you for choosing this repository for your first pull request 💖 !"